/*
 * ifaceSettings.h
 *
 *  Created on: 05 мая 2016 г.
 *      Author: svalov
 */

#ifndef IFACESETTINGS_H_
#define IFACESETTINGS_H_

#define INTERFACE_STACK_SIZE configMINIMAL_STACK_SIZE*2
//beacons frequency

#define STORED_NEIGHBORS				10
#define DATA_NEED_RESPONSE 				1
#define WAITING_RESPONSE_TIMEOUT 		1000
#define TRANSMIT_TIMEOUT				WAITING_RESPONSE_TIMEOUT*10;
#define BEACON_RSSI_MIN_THRESHOLD		-90
#define BEACON_RSSI_MAX_THRESHOLD		100

#define BEACON_CHANNEL 					0
#define BEACON_SEED						0xa3fc
#define BEACON_POWER					15 //LORA_MAXOUTPUTPOWER
#define	BEACON_DEFAULT_ADDRESS			0x00000000
#define	BEACON_DEFAULT_PAYLOAD_SIZE		0
#define BEACON_SEND_INTERVAL			5000
#define BEACON_SEND_DEVIATION			500
#define BEACON_LISTEN_TIMEOUT			BEACON_SEND_INTERVAL
#define BEACON_SEND_STARTUP_INTERVAL	1000
#define BEACON_SEND_STARTUP_DURATION	(BEACON_SEND_STARTUP_INTERVAL*10)
#define BEACON_LISTEN_STARTUP			(BEACON_SEND_STARTUP_DURATION)
#define BEACON_LISTEN_FORCE				(BEACON_SEND_INTERVAL*10)
#define LORA_RESTART_TIMEOUT			(BEACON_LISTEN_FORCE*10)

//remove neighbor after MAX_LAST_SEND_TRYS send without response
#define MAX_LAST_SEND_TRYS				3
#define TX_TIMEOUT_COEF					2

#endif /* IFACESETTINGS_H_ */
